config/routes.rb
Rails.application.routes.draw do

  root 'home#index', as: :home
  
  get 'people/a-z' => 'person_atoz#index', as: :person_atoz_list
  get 'people/a-z/:letter' => 'person_atoz#show', as: :person_atoz_show
  
  get 'people' => 'person#index', as: :person_list
  get 'people/:person' => 'person#show', as: :person_show
  
  get 'administrations' => 'administration#index', as: :administration_list
  get 'administrations/:administration' => 'administration#show', as: :administration_show
  
  get 'special-remainders' => 'special_remainder#index', as: :special_remainder_list
  get 'special-remainders/:special_remainder' => 'special_remainder#show', as: :special_remainder_show
  
  get 'ranks' => 'rank#index', as: :rank_list
  get 'ranks/:rank' => 'rank#show', as: :rank_show
  
  get 'peerage-types' => 'peerage_type#index', as: :peerage_type_list
  get 'peerage-types/:peerage_type' => 'peerage_type#show', as: :peerage_type_show
  
  get 'peerage-types/:peerage_type/a-z' => 'peerage_type_atoz#index', as: :peerage_type_atoz_list
  get 'peerage-types/:peerage_type/a-z/:letter' => 'peerage_type_atoz#show', as: :peerage_type_atoz_show
  
  get 'jurisdictions' => 'jurisdiction#index', as: :jurisdiction_list
  get 'jurisdictions/:jurisdiction' => 'jurisdiction#show', as: :jurisdiction_show
  
  get 'announcement-types' => 'announcement_type#index', as: :announcement_type_list
  get 'announcement-types/:announcement_type' => 'announcement_type#show', as: :announcement_type_show
  
  get 'announcements' => 'announcement#index', as: :announcement_list
  get 'announcements/:announcement' => 'announcement#show', as: :announcement_show
  
  get 'peerages/a-z' => 'peerage_atoz#index', as: :peerage_atoz_list
  get 'peerages/a-z/:letter' => 'peerage_atoz#show', as: :peerage_atoz_show
  
  get 'peerages' => 'peerage#index', as: :peerage_list
  get 'peerages/:peerage' => 'peerage#show', as: :peerage_show
  
  get 'peerage-holdings' => 'peerage_holding#index', as: :peerage_holding_list
  get 'peerage-holdings/:peerage_holding' => 'peerage_holding#show', as: :peerage_holding_show
  
  get 'letters-patent' => 'letters_patent#index', as: :letters_patent_list
  get 'letters-patent/:letters_patent' => 'letters_patent#show', as: :letters_patent_show
  
  get 'law-lord-incumbencies' => 'law_lord_incumbency#index', as: :law_lord_incumbency_list
  get 'law-lord-incumbencies/:law_lord_incumbency' => 'law_lord_incumbency#show', as: :law_lord_incumbency_show
  
  get 'monarchs' => 'monarch#index', as: :monarch_list
  get 'monarchs/:monarch' => 'monarch#show', as: :monarch_show
  
  get 'reigns' => 'reign#index', as: :reign_list
  get 'reigns/:reign' => 'reign#show', as: :reign_show
  
  get 'kingdoms' => 'kingdom#index', as: :kingdom_list
  get 'kingdoms/:kingdom' => 'kingdom#show', as: :kingdom_show
  
  get 'kingdoms/:kingdom/peerages' => 'kingdom_peerage#index', as: :kingdom_peerage_list
  
  get 'kingdoms/:kingdom/peerages/a-z' => 'kingdom_peerage_atoz#index', as: :kingdom_peerage_atoz_list
  get 'kingdoms/:kingdom/peerages/a-z/:letter' => 'kingdom_peerage_atoz#show', as: :kingdom_peerage_atoz_show
  
  get 'kingdoms/:kingdom/ranks' => 'kingdom_rank#index', as: :kingdom_rank_list
  get 'kingdoms/:kingdom/ranks/:rank' => 'kingdom_rank#show', as: :kingdom_rank_show
  
  get 'kingdoms/:kingdom/reigns' => 'kingdom_reign#index', as: :kingdom_reign_list
  
  get 'kingdoms/:kingdom/letters-patent' => 'kingdom_letters_patent#index', as: :kingdom_letters_patent_list
  
  get 'meta' => 'meta#index', as: :meta_list
  get 'meta/about' => 'meta#about', as: :meta_about
  get 'meta/iaq' => 'meta#iaq', as: :meta_iaq
  get 'meta/schema' => 'meta#schema', as: :meta_schema
  get 'meta/suspected-data-errors' => 'meta#suspected_data_errors', as: :meta_suspected_data_errors
  get 'meta/report' => 'meta#report', as: :meta_report

end

app/controllers/meta_controller.rb
class MetaController < ApplicationController
  
  def index
  end
  
  def about
  end
  
  def iaq
  end
  
  def schema
  end
  
  def suspected_data_errors
  end
  
  def report
    @extinct_hereditary_peerages = Peerage.all.select( 'p.*, count(ph.id) as holder_count' ).joins( 'as p, peerage_holdings as ph' ).where( 'p.id = ph.peerage_id' ).where( 'p.last_number is not null' ).where( 'p.last_number > 1' ).group( 'p.id' ).order( 'p.last_number desc')
    
    @non_extinct_hereditary_peerages = Peerage.all.select( 'p.*, lp.patent_on as patent_on, count(ph.id) as holder_count' ).joins( 'as p, peerage_holdings as ph, letters_patents as lp' ).where( 'p.id = ph.peerage_id' ).where( 'p.last_number is null' ).where( 'p.peerage_type_id not in (1,5,6)' ).where( 'p.letters_patent_id = lp.id').group( 'p.id, lp.id' ).order( 'lp.patent_on' )
  end
end

app/helpers/meta_helper.rb
module MetaHelper
end

app/views/meta/_extinct_peerage.html.erb
<tr>
	<%= content_tag( 'td', extinct_peerage.id ) %>
	<%= content_tag( 'td', link_to( extinct_peerage.display_title, peerage_show_url( :peerage => extinct_peerage ) ) ) %>
	<%= content_tag( 'td', extinct_peerage.last_number ) %>
	<%= content_tag( 'td', extinct_peerage.holder_count ) %>
</tr>

app/views/meta/_non_extinct_peerage.html.erb
<tr>
	<%= content_tag( 'td', non_extinct_peerage.id ) %>
	<%= content_tag( 'td', non_extinct_peerage.patent_on.strftime( '%-d %B %Y') ) %>
	<%= content_tag( 'td', non_extinct_peerage.holder_count ) %>
</tr>

app/views/meta/about.html.erb
<%= content_tag( 'h1', 'About this application' ) %>

<%= content_tag( 'p', "This application is based on data collated by #{link_to( 'David Beamish', 'https://twitter.com/clerkly' )}. The information was originally published at #{link_to( 'United Kingdom peerage creations 1801 to 2020: peerages.info', 'http://peerages.info/' )}.".html_safe ) %>

<%= content_tag( 'p', "Whilst the data at peerages.info is peerage centric, we have decided to normalise people from the peerages they were granted. This has been done on the assumption that every record sharing the same set of forenames, surname, date of birth, date of death - where present - and gender represents the same person. This logic has been checked and cleared by David Beamish." ) %>

<%= content_tag( 'p', "Normalising people allows us to give each person an identifier - and a URL - meaning we can link to them and link them to other data sets. For example: it makes it possible to publish claims of equivalence to and from people identified by the #{link_to( 'Rush data', 'https://membersafter1832.historyofparliamentonline.org/' )} and #{link_to( 'Wikidata', 'https://www.wikidata.org/wiki/Wikidata:Main_Page')}.".html_safe ) %>

<%= content_tag( 'p', "In normalising people, we have created a table called 'peerage holdings' which allows us to describe multiple people holding the same peerage over time. As yet we do not have data for this and are only capturing persons first holding a peerage." ) %>

app/views/meta/iaq.html.erb
<%= content_tag( 'h1', 'Infrequently Asked Questions' ) %>
<ol>
	<li>
		<%= content_tag( 'p', "The source data has peerages having subsidiary titles. This doesn't work for titles with different special remainders where the peerages might part company as the different titles move down different lines of inheritance. See peerages under #{link_to( 'this letters patent', 'http://peerages.herokuapp.com/letters-patent/2727' )} for example. peerages.info has 'a subsidiary peerage created by the same letters patent as a higher-ranking peerage'. Are parent and subsidiary peerages created by the same letters patent or different letters patent issued on the same day?".html_safe ) %>
		<%= content_tag( 'p', "Peerages granted to the same person on the same day are issued in the same letters patent. The same person may be granted different peerages at different points in time. They may hold more than one peerage of the same rank. In this case they should be listed in rank order, then by date of letters patent, earliest first." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "All subsidiary peerages have the same date for issue of letters patent as their parent peerage, except for the current #{link_to( 'Duke of Cambridge', peerage_show_url( :peerage => 2740 ) )} whose main peerage has a letters patent date of 26/05/2011, with two subsidiary titles - the #{link_to( 'Earl of Strathearn', peerage_show_url( :peerage => 3106 ) )} and #{link_to( 'Lord Carrickfergus', peerage_show_url( :peerage => 3099 ) )} - having a letters patent date of 29/04/2011. We have checked the London Gazette and found a single announcement. For now, we have assumed incorrect dates on the subsidiaries and combined them into the same letters patent as the 'parent' peerage. Is this a data entry error or can there be a gap between issuing of parent and subsidiary peerages?".html_safe ) %>
		<%= content_tag( 'p', "We believe this was a data entry error. All three peerages should have had a letters patent date of 26/05/2011." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Are there - genderless- labels for all ranks? If so, what are they?" ) %>
		<%= content_tag( 'p', "Princedom / Dukedom / Marquessate / Earldom / Viscountcy / Barony." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Is it possible for peerages of different types to be created in the same letters patent?" ) %>
		<%= content_tag( 'p', "There is nothing to preclude this but no known examples. It is possible to imagine an hereditary peerage being created which would not allow for a seat in the Lords, alongside a life peerage which would. We have no moved peerage type back to be a property of peerage rather than the letters patent, so should be able to cope with this eventuality." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Is there ever an announcement upon inheritance of a peerage?" ) %>
		<%= content_tag( 'p', "No." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "#{link_to( 'Category 5 of special remainders', special_remainder_show_url( :special_remainder => 5 ) )} implies peerages grouped have special remainders but is used to group peerages with subsidiary titles with special remainders. Should this category exist?".html_safe ) %>
		<%= content_tag( 'p', "#{link_to( 'Category 5 of special remainders', special_remainder_show_url( :special_remainder => 5 ) )} groups peerages sharing a letters patent with a second peerage having a special remainder, but the peerages grouped do not themselves have special remainders. Category 5 should be removed.".html_safe ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Is there a better word than ordinality for the Xth Viscount Y?" ) %>
		<%= content_tag( 'p', "No other term is in common use. Ordinality is fine." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Is there a word for the 'of' in Earl of X?" ) %>
		<%= content_tag( 'p', "This usually distinguishes between Earl of Place and Earl Surname, but not exclusively. Continuing to call the field 'of_title' is fine." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Is it possible for a peer to change their name whilst holding a peerage?" ) %>
		<%= content_tag( 'p', "We need to deal with this from a personal perspective but not in terms of the peerage title. Letters patent say the person shall, 'henceforth be known as'." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Besides death, how else might a peerage holding end?" ) %>
		<%= content_tag( 'p', "Historically a peer might be declared attainted though this often coincided with a death penalty and the extinction of the peerage. Under the Peerage Act 1963, a peer might disclaim the peerage. This would have the effect of wiping out any record of that person holding the peerage, although the College of Arms still retains a record of the holding. Anthony Neil Wedgwood Benn is still regarded by the College of Arms as the 2nd Viscount Stansgate. The Title Deprivation Act 1917  deprived enemy aliens of peerages, allowing holders and their descendants to petition the Crown for reinstatement. In such cases the peerages were suspended and did not become extinct. A peerage may also be merged with the Crown, for example, the title of Duke of Edinburgh is now held by the Prince of Wales but will 'merge in the Crown' when he becomes king, and thus the title will be available for re-use." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "How should one title a peerage - as opposed to a peer holding a peerage - if that peerage can move between genders?" ) %>
		<%= content_tag( 'p', "Title (Genderless rank) has been suggested and agreed with, for example: Curzon of Kedleston (Earldom)" ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Are subsidiary peerages under the same letters patent also announced?" ) %>
		<%= content_tag( 'p', "Yes. Subsidiary peerages under the same letters patent are announced together." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "What is the number attribute on announcements?" ) %>
		<%= content_tag( 'p', "David's plan was to list the number of peerages announced in a list, but he never got round to populating it other than with a few in 2001." ) %>
	</li>
	
	<li>
		<%= content_tag( 'p', "Do we need to model writs of acceleration and if so how?" ) %>
		<%= content_tag( 'p', "Having spoken to Ned, the decision is no. Writs of acceleration allow a person having more than one peerage to transfer the holding of their lowest ranked peerage to the heir of that peerage before the death of the current holder. This allowing the heir sit in the House at the same time as their father. Such writs were granted by the Lord Chancellor, following a petition to the Queen. Providing the data is managed correctly, we should be able to identify persons in receipt of a writ of acceleration by their holding starting at an earlier date than the date of death of the previous holder." ) %>
	</li>
</ol>

<%= content_tag( 'h2', 'Unanswered' ) %>
<ol>
	
	<li>
		<%= content_tag( 'p', "Some peerages point to announcements of a type that are not present in the data. Can we create these?" ) %>
		<%= content_tag( 'p', "Announcement types should be coded as one of A B C D G L N O P R T V W. Are other letters in use?" ) %>
	</li>
</ol>

app/views/meta/index.html.erb
<%= content_tag( 'h1', 'Meta' ) %>
<ol>
	<%= content_tag( 'li', link_to( 'About', meta_about_url ) ) %>
	<%= content_tag( 'li', link_to( 'Infrequently Asked Questions', meta_iaq_url ) ) %>
	<%= content_tag( 'li', link_to( 'Schema', meta_schema_url ) ) %>
	<%= content_tag( 'li', link_to( 'Source code', 'https://github.com/ukparliament/peerages' ) ) %>
	<%= content_tag( 'li', link_to( 'Suspected data errors', meta_suspected_data_errors_url ) ) %>
	<%= content_tag( 'li', link_to( 'Report', meta_report_url ) ) %>
</ol>

app/views/meta/report.html.erb
<%= content_tag( 'h1', 'Peerage report' ) %>

<div id="extinct">
	<%= content_tag( 'h2', "Extinct hereditary peerages" ) %>
	<table>
		<thead>
			<tr>
				<%= content_tag( 'td', 'Peerage ID' ) %>
				<%= content_tag( 'td', 'Peerage' ) %>
				<%= content_tag( 'td', 'Number of holders' ) %>
				<%= content_tag( 'td', 'Number of holders populated' ) %>
			</tr>
		</thead>
		<tbody>
			<%= render :partial => 'extinct_peerage', :collection => @extinct_hereditary_peerages %>
		</tbody>
	</table>
</div>

<div id="non-extinct">
	<%= content_tag( 'h2', 'Non-extinct hereditary peerages' ) %>
	<table>
		<thead>
			<tr>
				<%= content_tag( 'td', 'Peerage ID' ) %>
				<%= content_tag( 'td', 'Peerage' ) %>
				<%= content_tag( 'td', 'Patent on' ) %>
				<%= content_tag( 'td', 'Number of holders populated' ) %>
			</tr>
		</thead>
		<tbody>
			<%= render :partial => 'non_extinct_peerage', :collection => @non_extinct_hereditary_peerages %>
		</tbody>
	</table>
</div>

app/views/meta/schema.html.erb
<%= content_tag( 'h1', 'Database schema' ) %>
<%= content_tag( 'p', "#{link_to( 'Postgres data dump', '/peerages/peerages.sql.zip' )}.".html_safe ) %>
<%= link_to( image_tag( '/peerages/schema.png' ), '/peerages/schema.png' ) %>

app/views/meta/suspected_data_errors.html.erb
<%= content_tag( 'h1', 'Suspected data errors' ) %>

<%= content_tag( 'p', 'Checked and fixed at source.' ) %>