config/routes.rb
Rails.application.routes.draw do

  root 'home#index', as: :home
  
  get 'people/a-z' => 'person_atoz#index', as: :person_atoz_list
  get 'people/a-z/:letter' => 'person_atoz#show', as: :person_atoz_show
  
  get 'people' => 'person#index', as: :person_list
  get 'people/:person' => 'person#show', as: :person_show
  
  get 'administrations' => 'administration#index', as: :administration_list
  get 'administrations/:administration' => 'administration#show', as: :administration_show
  
  get 'special-remainders' => 'special_remainder#index', as: :special_remainder_list
  get 'special-remainders/:special_remainder' => 'special_remainder#show', as: :special_remainder_show
  
  get 'ranks' => 'rank#index', as: :rank_list
  get 'ranks/:rank' => 'rank#show', as: :rank_show
  
  get 'peerage-types' => 'peerage_type#index', as: :peerage_type_list
  get 'peerage-types/:peerage_type' => 'peerage_type#show', as: :peerage_type_show
  
  get 'peerage-types/:peerage_type/a-z' => 'peerage_type_atoz#index', as: :peerage_type_atoz_list
  get 'peerage-types/:peerage_type/a-z/:letter' => 'peerage_type_atoz#show', as: :peerage_type_atoz_show
  
  get 'jurisdictions' => 'jurisdiction#index', as: :jurisdiction_list
  get 'jurisdictions/:jurisdiction' => 'jurisdiction#show', as: :jurisdiction_show
  
  get 'announcement-types' => 'announcement_type#index', as: :announcement_type_list
  get 'announcement-types/:announcement_type' => 'announcement_type#show', as: :announcement_type_show
  
  get 'announcements' => 'announcement#index', as: :announcement_list
  get 'announcements/:announcement' => 'announcement#show', as: :announcement_show
  
  get 'peerages/a-z' => 'peerage_atoz#index', as: :peerage_atoz_list
  get 'peerages/a-z/:letter' => 'peerage_atoz#show', as: :peerage_atoz_show
  
  get 'peerages' => 'peerage#index', as: :peerage_list
  get 'peerages/:peerage' => 'peerage#show', as: :peerage_show
  
  get 'peerage-holdings' => 'peerage_holding#index', as: :peerage_holding_list
  get 'peerage-holdings/:peerage_holding' => 'peerage_holding#show', as: :peerage_holding_show
  
  get 'letters-patent' => 'letters_patent#index', as: :letters_patent_list
  get 'letters-patent/:letters_patent' => 'letters_patent#show', as: :letters_patent_show
  
  get 'law-lord-incumbencies' => 'law_lord_incumbency#index', as: :law_lord_incumbency_list
  get 'law-lord-incumbencies/:law_lord_incumbency' => 'law_lord_incumbency#show', as: :law_lord_incumbency_show
  
  get 'monarchs' => 'monarch#index', as: :monarch_list
  get 'monarchs/:monarch' => 'monarch#show', as: :monarch_show
  
  get 'reigns' => 'reign#index', as: :reign_list
  get 'reigns/:reign' => 'reign#show', as: :reign_show
  
  get 'kingdoms' => 'kingdom#index', as: :kingdom_list
  get 'kingdoms/:kingdom' => 'kingdom#show', as: :kingdom_show
  
  get 'kingdoms/:kingdom/peerages' => 'kingdom_peerage#index', as: :kingdom_peerage_list
  
  get 'kingdoms/:kingdom/peerages/a-z' => 'kingdom_peerage_atoz#index', as: :kingdom_peerage_atoz_list
  get 'kingdoms/:kingdom/peerages/a-z/:letter' => 'kingdom_peerage_atoz#show', as: :kingdom_peerage_atoz_show
  
  get 'kingdoms/:kingdom/ranks' => 'kingdom_rank#index', as: :kingdom_rank_list
  get 'kingdoms/:kingdom/ranks/:rank' => 'kingdom_rank#show', as: :kingdom_rank_show
  
  get 'kingdoms/:kingdom/reigns' => 'kingdom_reign#index', as: :kingdom_reign_list
  
  get 'kingdoms/:kingdom/letters-patent' => 'kingdom_letters_patent#index', as: :kingdom_letters_patent_list
  
  get 'meta' => 'meta#index', as: :meta_list
  get 'meta/about' => 'meta#about', as: :meta_about
  get 'meta/iaq' => 'meta#iaq', as: :meta_iaq
  get 'meta/schema' => 'meta#schema', as: :meta_schema
  get 'meta/suspected-data-errors' => 'meta#suspected_data_errors', as: :meta_suspected_data_errors
  get 'meta/report' => 'meta#report', as: :meta_report

end

app/models/peerage_holding.rb
class PeerageHolding < ActiveRecord::Base
  
  belongs_to :person
  belongs_to :peerage
end

app/controllers/peerage_holding_controller.rb
class PeerageHoldingController < ApplicationController
  
  def index
  end
  
  def show
    peerage_holding = params[:peerage_holding]
    @peerage_holding = PeerageHolding.find( peerage_holding )
  end
end

app/helpers/peerage_holding_helper.rb
module PeerageHoldingHelper
end

app/views/peerage_holding/_peerage_holding.html.erb
<tr>
	<%= content_tag( 'td', link_to( peerage_holding.ordinality.ordinalize, peerage_holding_show_url( :peerage_holding => peerage_holding ) ) ) %>
	<td>
		<% if peerage_holding.person.surname -%>
			<%= link_to( peerage_holding.person.surname, person_show_url( :person => peerage_holding.person ) ) %>
		<% else -%>
			-
		<% end -%>
	</td>
	<%= content_tag( 'td', link_to( peerage_holding.person.forenames, person_show_url( :person => peerage_holding.person ) ) ) %>
	<td>
		<% if peerage_holding.start_on -%>
			<%= peerage_holding.start_on.strftime( '%-d %B %Y' ) %>
		<% else -%>
			-
		<% end -%>
	</td>
	<td>
		<% if peerage_holding.end_on -%>
			<%= peerage_holding.end_on.strftime( '%-d %B %Y' ) %>
		<% else -%>
			-
		<% end -%>
	</td>
</tr>

app/views/peerage_holding/index.html.erb
<%= content_tag( 'h1', 'Peerage holdings' ) %>

<%= content_tag( 'p', 'Nothing to see here.' ) %>

app/views/peerage_holding/show.html.erb
<%= content_tag( 'h1', "#{link_to( @peerage_holding.person.display_name, person_show_url( :person => @peerage_holding.person ) )}, #{@peerage_holding.ordinality.ordinalize} #{link_to( @peerage_holding.peerage.gendered_display_title(@peerage_holding.person.gender ), peerage_show_url( :peerage => @peerage_holding.peerage ) ) }".html_safe ) %>

<% if @peerage_holding.end_on and @peerage_holding.start_on -%>
	<%= content_tag( 'p', "From #{@peerage_holding.start_on.strftime( '%-d %B %Y')} to #{@peerage_holding.end_on.strftime( '%-d %B %Y')}." ) %>
<% elsif @peerage_holding.start_on =%>
	<%= content_tag( 'p', "From #{@peerage_holding.start_on.strftime( '%-d %B %Y')}." ) %>
<% elsif @peerage_holding.end_on =%>
	<%= content_tag( 'p', "Held until #{@peerage_holding.end_on.strftime( '%-d %B %Y')}." ) %>
<% end -%>

<% if @peerage_holding.introduced_on -%>
	<%= content_tag( 'p', "Introduced to the House of Lords on #{@peerage_holding.introduced_on.strftime( '%-d %B %Y')}." ) %>
<% end -%>

<%= content_tag( 'p', "Note: #{@peerage_holding.notes}" ) if @peerage_holding.notes %>