config/routes.rb
Rails.application.routes.draw do

  root 'home#index', as: :home
  
  get 'people/a-z' => 'person_atoz#index', as: :person_atoz_list
  get 'people/a-z/:letter' => 'person_atoz#show', as: :person_atoz_show
  
  get 'people' => 'person#index', as: :person_list
  get 'people/:person' => 'person#show', as: :person_show
  
  get 'administrations' => 'administration#index', as: :administration_list
  get 'administrations/:administration' => 'administration#show', as: :administration_show
  
  get 'special-remainders' => 'special_remainder#index', as: :special_remainder_list
  get 'special-remainders/:special_remainder' => 'special_remainder#show', as: :special_remainder_show
  
  get 'ranks' => 'rank#index', as: :rank_list
  get 'ranks/:rank' => 'rank#show', as: :rank_show
  
  get 'peerage-types' => 'peerage_type#index', as: :peerage_type_list
  get 'peerage-types/:peerage_type' => 'peerage_type#show', as: :peerage_type_show
  
  get 'peerage-types/:peerage_type/a-z' => 'peerage_type_atoz#index', as: :peerage_type_atoz_list
  get 'peerage-types/:peerage_type/a-z/:letter' => 'peerage_type_atoz#show', as: :peerage_type_atoz_show
  
  get 'jurisdictions' => 'jurisdiction#index', as: :jurisdiction_list
  get 'jurisdictions/:jurisdiction' => 'jurisdiction#show', as: :jurisdiction_show
  
  get 'announcement-types' => 'announcement_type#index', as: :announcement_type_list
  get 'announcement-types/:announcement_type' => 'announcement_type#show', as: :announcement_type_show
  
  get 'announcements' => 'announcement#index', as: :announcement_list
  get 'announcements/:announcement' => 'announcement#show', as: :announcement_show
  
  get 'peerages/a-z' => 'peerage_atoz#index', as: :peerage_atoz_list
  get 'peerages/a-z/:letter' => 'peerage_atoz#show', as: :peerage_atoz_show
  
  get 'peerages' => 'peerage#index', as: :peerage_list
  get 'peerages/:peerage' => 'peerage#show', as: :peerage_show
  
  get 'peerage-holdings' => 'peerage_holding#index', as: :peerage_holding_list
  get 'peerage-holdings/:peerage_holding' => 'peerage_holding#show', as: :peerage_holding_show
  
  get 'letters-patent' => 'letters_patent#index', as: :letters_patent_list
  get 'letters-patent/:letters_patent' => 'letters_patent#show', as: :letters_patent_show
  
  get 'law-lord-incumbencies' => 'law_lord_incumbency#index', as: :law_lord_incumbency_list
  get 'law-lord-incumbencies/:law_lord_incumbency' => 'law_lord_incumbency#show', as: :law_lord_incumbency_show
  
  get 'monarchs' => 'monarch#index', as: :monarch_list
  get 'monarchs/:monarch' => 'monarch#show', as: :monarch_show
  
  get 'reigns' => 'reign#index', as: :reign_list
  get 'reigns/:reign' => 'reign#show', as: :reign_show
  
  get 'kingdoms' => 'kingdom#index', as: :kingdom_list
  get 'kingdoms/:kingdom' => 'kingdom#show', as: :kingdom_show
  
  get 'kingdoms/:kingdom/peerages' => 'kingdom_peerage#index', as: :kingdom_peerage_list
  
  get 'kingdoms/:kingdom/peerages/a-z' => 'kingdom_peerage_atoz#index', as: :kingdom_peerage_atoz_list
  get 'kingdoms/:kingdom/peerages/a-z/:letter' => 'kingdom_peerage_atoz#show', as: :kingdom_peerage_atoz_show
  
  get 'kingdoms/:kingdom/ranks' => 'kingdom_rank#index', as: :kingdom_rank_list
  get 'kingdoms/:kingdom/ranks/:rank' => 'kingdom_rank#show', as: :kingdom_rank_show
  
  get 'kingdoms/:kingdom/reigns' => 'kingdom_reign#index', as: :kingdom_reign_list
  
  get 'kingdoms/:kingdom/letters-patent' => 'kingdom_letters_patent#index', as: :kingdom_letters_patent_list
  
  get 'meta' => 'meta#index', as: :meta_list
  get 'meta/about' => 'meta#about', as: :meta_about
  get 'meta/iaq' => 'meta#iaq', as: :meta_iaq
  get 'meta/schema' => 'meta#schema', as: :meta_schema
  get 'meta/suspected-data-errors' => 'meta#suspected_data_errors', as: :meta_suspected_data_errors
  get 'meta/report' => 'meta#report', as: :meta_report

end

app/models/letters_patent.rb
class LettersPatent < ActiveRecord::Base
  
  # Legislation covering letters patent
  # https://www.legislation.gov.uk/uksi/1992/1730/made
  
  belongs_to :administration
  belongs_to :peerage_type
  belongs_to :announcement
  belongs_to :person
  belongs_to :letters_patent_time
  belongs_to :kingdom
  belongs_to :reign
  
  def peerages
    Peerage.all.select( 'p.*' ).joins( 'as p, ranks as r' ).where( 'letters_patent_id = ?', self.id).where( 'p.rank_id = r.id' ).order( 'r.degree' )
  end
  
  def previous_full_title
    if self.previous_rank
      previous_title = self.previous_rank + ' ' + self.previous_title
    else
      previous_title = '-'
    end
    previous_title
  end
  
  def prime_minister_reverse_ordinally
    pm = prime_minister_inline.gsub(/(.*)\((.*)\)/) {|s| $2.to_i.ordinalize + " " +  $1 + " administration"}
    if pm == prime_minister_inline
      pm = prime_minister_inline + ' administration'
    end
    pm
  end
  
  def previous_kingdom
    Kingdom.find( self.previous_kingdom_id ) if self.previous_kingdom_id
  end
  
  def peerage_full_title
    peerage_full_title = ''
    peerage_full_title += 'of ' if self.peerage_of_title_inline
    peerage_full_title += self.peerage_title_inline if self.peerage_title_inline
    peerage_full_title += ' (' + self.rank_label_inline + ')' if self.rank_label_inline
    peerage_full_title
  end
  
  # adapt to take prefix and suffix off lp record and combine with name names from person model from inline query
  def person_full_name
    person_full_name = ''
    person_full_name += self.person_prefix + ' ' if self.person_prefix
    person_full_name += self.person_forenames_inline if self.person_forenames_inline
    person_full_name += ' ' + self.person_surname_inline if self.person_surname_inline
    person_full_name += ', ' + self.person_suffix + ' ' if self.person_suffix
    person_full_name
  end
  
  def peerage_extinction_label
    peerage_extinction_label = ''
    if self.peerage_extinct_on_inline
      peerage_extinction_label = self.peerage_extinct_on_inline.strftime( '%-d %B %Y')
      peerage_extinction_label += ' (with the ' + self.peerage_last_number_inline.ordinalize + ' holder)'
    else
      peerage_extinction_label = '-'
    end
    peerage_extinction_label
  end
end

app/controllers/letters_patent_controller.rb
class LettersPatentController < ApplicationController
  
  def index
    @letters_patent = LettersPatent.find_by_sql( 
      "
        SELECT 
          lp.*,
          
          kingdom_join.kingdom_id AS kingdom_id_inline,
          kingdom_join.kingdom_name AS kingdom_name_inline,
          
          reign_join.reign_title AS reign_title_inline,
          reign_join.reign_id AS reign_id_inline,
          
          letters_patent_time_join.letters_patent_time_label AS letters_patent_time_inline,
          
          announcement_join.administration_id AS administration_id_inline,
          announcement_join.prime_minister AS prime_minister_inline,
          
          peerage_join.peerage_id AS peerage_id_inline,
          peerage_join.peerage_of_title AS peerage_of_title_inline,
          peerage_join.peerage_title AS peerage_title_inline,
          peerage_join.peerage_extinct_on AS peerage_extinct_on_inline,
          peerage_join.peerage_last_number AS peerage_last_number_inline,
          peerage_join.rank_label AS rank_label_inline,
          peerage_join.peerage_type_id_inline AS peerage_type_id_inline,
          peerage_join.peerage_type_name_inline AS peerage_type_name_inline,
          
          person_join.person_forenames AS person_forenames_inline,
          person_join.person_surname AS person_surname_inline,
          person_join.person_date_of_death AS person_date_of_death_inline
          
        FROM letters_patents lp
        
        JOIN (
          SELECT 
            k.id as kingdom_id,
            k.name as kingdom_name
          FROM kingdoms k
        ) kingdom_join
        ON kingdom_join.kingdom_id = lp.kingdom_id
        
        LEFT JOIN (
          SELECT 
            r.title as reign_title,
            r.id as reign_id
          FROM reigns r
        ) reign_join
        ON reign_join.reign_id = lp.reign_id
          
        LEFT JOIN (
          SELECT
            lpt.id AS patent_time_id,
            lpt.label AS letters_patent_time_label
          FROM letters_patent_times lpt
        ) letters_patent_time_join
        ON letters_patent_time_join.patent_time_id = lp.letters_patent_time_id
        
        LEFT JOIN (
          SELECT
            an.id AS announcement_id,
            ad.id AS administration_id,
            ad.prime_minister AS prime_minister
          FROM announcements an, administrations ad
          WHERE an.administration_id = ad.id
        ) announcement_join
        ON announcement_join.announcement_id = lp.announcement_id
        
        JOIN (
          SELECT
            DISTINCT ON (p.letters_patent_id) degree,
            p.letters_patent_id AS letters_patent_id,
            p.id AS peerage_id,
            p.of_title AS peerage_of_title,
            p.extinct_on AS peerage_extinct_on,
            p.last_number AS peerage_last_number,
            p.title AS peerage_title,
            r.label AS rank_label,
            pt.id AS peerage_type_id_inline,
            pt.name AS peerage_type_name_inline
          FROM peerages p, ranks r, peerage_types pt
          WHERE p.rank_id = r.id
          AND p.peerage_type_id = pt.id
          ORDER BY p.letters_patent_id, r.degree
        ) peerage_join
        ON peerage_join.letters_patent_id = lp.id
        
        JOIN (
          SELECT
            p.id AS person_id,
            p.forenames as person_forenames,
            p.surname as person_surname,
            p.date_of_death as person_date_of_death
            from people p
        ) person_join
        ON person_join.person_id = lp.person_id
        
        ORDER BY lp.patent_on, lp.ordinality_on_date;
      "
    )
    respond_to do |format|
      format.html
      format.tsv
    end
  end
  
  def show
    letters_patent = params[:letters_patent]
    @letters_patent = LettersPatent.find( letters_patent )
  end
end

app/helpers/letters_patent_helper.rb
module LettersPatentHelper
  
  def full_previous_title( letters_patent )
    full_previous_title = ''
    full_previous_title += letters_patent.previous_rank if letters_patent.previous_rank
    full_previous_title += ' of' if letters_patent.previous_of_title
    full_previous_title += ' ' + letters_patent.previous_title if letters_patent.previous_title
    if letters_patent.previous_kingdom
      full_previous_title += ' in the Peerage of the '
      full_previous_title += link_to( letters_patent.previous_kingdom.name, kingdom_show_url( :kingdom => letters_patent.previous_kingdom ) )
    end
    full_previous_title
  end
end

app/views/letters_patent/_letters_patent.html.erb
<li>
	<%= content_tag( 'h2', link_to( "Letters patent issued on #{letters_patent.patent_on.strftime( '%-d %B %Y')}", letters_patent_show_url( :letters_patent => letters_patent ) ) ) %>
	<%= content_tag( 'p', "To #{link_to( letters_patent.person.display_name, person_show_url( :person => letters_patent.person ) )}:".html_safe ) %>
	<ol>
		<%= render :partial => 'peerage/gendered_peerage', :collection => letters_patent.peerages, :locals => {:gender => letters_patent.person.gender} %>
	</ol>
</li>

app/views/letters_patent/_letters_patent.tsv.erb
<%= letters_patent.kingdom_name_inline %>	<%= letters_patent.reign_title_inline %>	<%= letters_patent.patent_on %>	<%= letters_patent.letters_patent_time_inline %>	<%= letters_patent.prime_minister_reverse_ordinally if letters_patent.administration_id_inline %>	<%= letters_patent.peerage_type_name_inline %>	<%= letters_patent.peerage_full_title %>	<%= letters_patent.person_full_name %>	<%= letters_patent.person_date_of_death_inline if letters_patent.person_date_of_death_inline %>	<%= letters_patent.previous_full_title %>	<%= letters_patent.peerage_extinct_on_inline %>

app/views/letters_patent/_letters_patent_table.html.erb
<tr>
	<%= content_tag( 'td', link_to( letters_patent_table.kingdom_name_inline, kingdom_show_url( :kingdom => letters_patent_table.kingdom_id_inline ) ) ) %>
	<td>
		<% if letters_patent_table.reign_title_inline -%>
			<%= link_to( letters_patent_table.reign_title_inline, reign_show_url( :reign => letters_patent_table.reign_id_inline ) ) %>
		<% else -%>
			-
		<% end -%>
	</td>
	<%= content_tag( 'td', link_to( letters_patent_table.patent_on.strftime( '%-d %B %Y'), letters_patent_show_url( :letters_patent => letters_patent_table) ) ) %>
	<td>
		<% if letters_patent_table.letters_patent_time_inline -%>
			<%= letters_patent_table.letters_patent_time_inline %>
		<% else -%>
			-
		<% end -%>
	</td>
	<td>
		<% if letters_patent_table.administration_id_inline -%>
			<%= link_to( letters_patent_table.prime_minister_reverse_ordinally, administration_show_url( letters_patent_table.administration_id_inline ) ) %>
		<% else -%>
			-
		<% end -%>
	</td>
	<%= content_tag( 'td', link_to( letters_patent_table.peerage_type_name_inline, peerage_type_show_url( :peerage_type => letters_patent_table.peerage_type_id_inline ) ) ) %>
	<%= content_tag( 'td', link_to( letters_patent_table.peerage_full_title, peerage_show_url( :peerage => letters_patent_table.peerage_id_inline ) ) ) %>
	<%= content_tag( 'td', link_to( letters_patent_table.person_full_name, person_show_url( :person => letters_patent_table.person_id ) ) ) %>
	<td>
		<% if letters_patent_table.person_date_of_death_inline %>
			<%= letters_patent_table.person_date_of_death_inline.strftime( '%-d %B %Y') %>
		<% else -%>
			-
		<% end -%>
	</td>
	<%= content_tag( 'td', letters_patent_table.previous_full_title ) %>
	<%= content_tag( 'td', letters_patent_table.peerage_extinction_label ) %>
</tr>

app/views/letters_patent/_table_header.html.erb
<thead>
	<tr>
		<%= content_tag( 'td', 'Kingdom' ) %>
		<%= content_tag( 'td', 'Reign' ) %>
		<%= content_tag( 'td', 'Issued on' ) %>
		<%= content_tag( 'td', 'Time' ) %>
		<%= content_tag( 'td', 'Announced during' ) %>
		<%= content_tag( 'td', 'Peerage type' ) %>
		<%= content_tag( 'td', 'Peerage' ) %>
		<%= content_tag( 'td', 'Issued to' ) %>
		<%= content_tag( 'td', 'Date of death' ) %>
		<%= content_tag( 'td', 'Previously' ) %>
		<%= content_tag( 'td', 'Extinct on' ) %>
	</tr>
</thead>

app/views/letters_patent/index.html.erb
<%= content_tag( 'h1', 'Letters Patent' ) %>

<%= content_tag( 'p', link_to( 'Download tab separated', letters_patent_list_url( :format => 'tsv' ) ) ) %>

<table>
	<%= render :partial => 'table_header' %>
	<tbody>
		<%= render :partial => 'letters_patent_table', :collection => @letters_patent %>
	</tbody>
</table>

app/views/letters_patent/index.tsv.erb
Kingdom	Reign	Issued on	Time	Announced during	Peerage type	Peerage	Issued to	Date of death	Previously	Extinct on
<%= render :partial => 'letters_patent/letters_patent', :collection => @letters_patent %>

app/views/letters_patent/show.html.erb
<%= content_tag( 'h1', "Letters patent issued on #{@letters_patent.patent_on.strftime( '%-d %B %Y')}" ) %>

<%= content_tag( 'p', "To #{link_to( @letters_patent.person.display_name, person_show_url( :person => @letters_patent.person ) )}.".html_safe ) %>

<% if @letters_patent.reign -%>
	<%= content_tag( 'p', "A peerage of the #{link_to( @letters_patent.kingdom.name, kingdom_show_url( :kingdom => @letters_patent.kingdom ) )}, during the #{link_to( "reign of #{@letters_patent.reign.title}", reign_show_url( :reign => @letters_patent.reign ) )}.".html_safe ) %>
<% else -%>
	<%= content_tag( 'p', "A peerage of the #{link_to( @letters_patent.kingdom.name, kingdom_show_url( :kingdom => @letters_patent.kingdom ) )}.".html_safe ) %>
<% end -%>

<%= content_tag( 'p', "Issued during the #{link_to( @letters_patent.administration.prime_minister, administration_show_url( :administration => @letters_patent.administration ) )} administration.".html_safe ) if @letters_patent.administration %>

<%= content_tag( 'p', "Announced on #{link_to( @letters_patent.announcement.announced_on.strftime( '%-d %B %Y'), announcement_show_url( :announcement => @letters_patent.announcement ) )} as part of a #{link_to( @letters_patent.announcement.announcement_type.name, announcement_type_show_url( :announcement_type => @letters_patent.announcement.announcement_type ) )}.".html_safe ) if @letters_patent.announcement %>

<%= content_tag( 'p', "Previously known as #{full_previous_title( @letters_patent )}.".html_safe ) if @letters_patent.previous_title  %>

<%= content_tag( 'h2', 'Peerages' ) %>
<ol>
	<%= render :partial => 'peerage/gendered_peerage', :collection => @letters_patent.peerages, :locals => {:gender => @letters_patent.person.gender} %>
</ol>

<% if @letters_patent.citations -%>
	<%= content_tag( 'h2', 'Citations' ) %>
	<%= content_tag( 'p', @letters_patent.citations ) %>
<% end -%>