config/routes.rb
Rails.application.routes.draw do

  root 'home#index', as: :home
  
  get 'people/a-z' => 'person_atoz#index', as: :person_atoz_list
  get 'people/a-z/:letter' => 'person_atoz#show', as: :person_atoz_show
  
  get 'people' => 'person#index', as: :person_list
  get 'people/:person' => 'person#show', as: :person_show
  
  get 'administrations' => 'administration#index', as: :administration_list
  get 'administrations/:administration' => 'administration#show', as: :administration_show
  
  get 'special-remainders' => 'special_remainder#index', as: :special_remainder_list
  get 'special-remainders/:special_remainder' => 'special_remainder#show', as: :special_remainder_show
  
  get 'ranks' => 'rank#index', as: :rank_list
  get 'ranks/:rank' => 'rank#show', as: :rank_show
  
  get 'peerage-types' => 'peerage_type#index', as: :peerage_type_list
  get 'peerage-types/:peerage_type' => 'peerage_type#show', as: :peerage_type_show
  
  get 'peerage-types/:peerage_type/a-z' => 'peerage_type_atoz#index', as: :peerage_type_atoz_list
  get 'peerage-types/:peerage_type/a-z/:letter' => 'peerage_type_atoz#show', as: :peerage_type_atoz_show
  
  get 'jurisdictions' => 'jurisdiction#index', as: :jurisdiction_list
  get 'jurisdictions/:jurisdiction' => 'jurisdiction#show', as: :jurisdiction_show
  
  get 'announcement-types' => 'announcement_type#index', as: :announcement_type_list
  get 'announcement-types/:announcement_type' => 'announcement_type#show', as: :announcement_type_show
  
  get 'announcements' => 'announcement#index', as: :announcement_list
  get 'announcements/:announcement' => 'announcement#show', as: :announcement_show
  
  get 'peerages/a-z' => 'peerage_atoz#index', as: :peerage_atoz_list
  get 'peerages/a-z/:letter' => 'peerage_atoz#show', as: :peerage_atoz_show
  
  get 'peerages' => 'peerage#index', as: :peerage_list
  get 'peerages/:peerage' => 'peerage#show', as: :peerage_show
  
  get 'peerage-holdings' => 'peerage_holding#index', as: :peerage_holding_list
  get 'peerage-holdings/:peerage_holding' => 'peerage_holding#show', as: :peerage_holding_show
  
  get 'letters-patent' => 'letters_patent#index', as: :letters_patent_list
  get 'letters-patent/:letters_patent' => 'letters_patent#show', as: :letters_patent_show
  
  get 'law-lord-incumbencies' => 'law_lord_incumbency#index', as: :law_lord_incumbency_list
  get 'law-lord-incumbencies/:law_lord_incumbency' => 'law_lord_incumbency#show', as: :law_lord_incumbency_show
  
  get 'monarchs' => 'monarch#index', as: :monarch_list
  get 'monarchs/:monarch' => 'monarch#show', as: :monarch_show
  
  get 'reigns' => 'reign#index', as: :reign_list
  get 'reigns/:reign' => 'reign#show', as: :reign_show
  
  get 'kingdoms' => 'kingdom#index', as: :kingdom_list
  get 'kingdoms/:kingdom' => 'kingdom#show', as: :kingdom_show
  
  get 'kingdoms/:kingdom/peerages' => 'kingdom_peerage#index', as: :kingdom_peerage_list
  
  get 'kingdoms/:kingdom/peerages/a-z' => 'kingdom_peerage_atoz#index', as: :kingdom_peerage_atoz_list
  get 'kingdoms/:kingdom/peerages/a-z/:letter' => 'kingdom_peerage_atoz#show', as: :kingdom_peerage_atoz_show
  
  get 'kingdoms/:kingdom/ranks' => 'kingdom_rank#index', as: :kingdom_rank_list
  get 'kingdoms/:kingdom/ranks/:rank' => 'kingdom_rank#show', as: :kingdom_rank_show
  
  get 'kingdoms/:kingdom/reigns' => 'kingdom_reign#index', as: :kingdom_reign_list
  
  get 'kingdoms/:kingdom/letters-patent' => 'kingdom_letters_patent#index', as: :kingdom_letters_patent_list
  
  get 'meta' => 'meta#index', as: :meta_list
  get 'meta/about' => 'meta#about', as: :meta_about
  get 'meta/iaq' => 'meta#iaq', as: :meta_iaq
  get 'meta/schema' => 'meta#schema', as: :meta_schema
  get 'meta/suspected-data-errors' => 'meta#suspected_data_errors', as: :meta_suspected_data_errors
  get 'meta/report' => 'meta#report', as: :meta_report

end

app/models/reign.rb
class Reign < ActiveRecord::Base
  
  belongs_to :kingdom
  
  def monarchs
    Monarch.all.select( 'm.*' ).joins( 'as m, reigning_monarchs as rm' ).where( 'rm.monarch_id = m.id' ).where( 'rm.reign_id = ?', self ).order( 'm.id' )
  end
  
  def reign_shared_with( monarch )
    Monarch.all.select( 'm.*' ).joins( 'as m, reigning_monarchs as rm' ).where( 'rm.monarch_id = m.id' ).where( 'rm.reign_id = ?', self ).where( 'm.id != ?', monarch.id ).order( 'm.id' ).first
  end
  
  def letters_patents
    LettersPatent.find_by_sql(
        "
          SELECT 
            lp.*,
          
            kingdom_join.kingdom_id AS kingdom_id_inline,
            kingdom_join.kingdom_name AS kingdom_name_inline,
          
            reign_join.reign_title AS reign_title_inline,
            reign_join.reign_id AS reign_id_inline,
          
            letters_patent_time_join.letters_patent_time_label AS letters_patent_time_inline,
          
            announcement_join.administration_id AS administration_id_inline,
            announcement_join.prime_minister AS prime_minister_inline,
          
            peerage_join.peerage_id AS peerage_id_inline,
            peerage_join.peerage_of_title AS peerage_of_title_inline,
            peerage_join.peerage_title AS peerage_title_inline,
            peerage_join.peerage_extinct_on AS peerage_extinct_on_inline,
            peerage_join.peerage_last_number AS peerage_last_number_inline,
            peerage_join.rank_label AS rank_label_inline,
            peerage_join.peerage_type_id_inline AS peerage_type_id_inline,
            peerage_join.peerage_type_name_inline AS peerage_type_name_inline,
          
            person_join.person_forenames AS person_forenames_inline,
            person_join.person_surname AS person_surname_inline,
            person_join.person_date_of_death AS person_date_of_death_inline
          
          FROM letters_patents lp
        
          JOIN (
            SELECT 
              k.id as kingdom_id,
              k.name as kingdom_name
            FROM kingdoms k
          ) kingdom_join
          ON kingdom_join.kingdom_id = lp.kingdom_id
        
          LEFT JOIN (
            SELECT 
              r.title as reign_title,
              r.id as reign_id
            FROM reigns r
          ) reign_join
          ON reign_join.reign_id = lp.reign_id
          
          LEFT JOIN (
            SELECT
              lpt.id AS patent_time_id,
              lpt.label AS letters_patent_time_label
            FROM letters_patent_times lpt
          ) letters_patent_time_join
          ON letters_patent_time_join.patent_time_id = lp.letters_patent_time_id
        
          LEFT JOIN (
            SELECT
              an.id AS announcement_id,
              ad.id AS administration_id,
              ad.prime_minister AS prime_minister
            FROM announcements an, administrations ad
            WHERE an.administration_id = ad.id
          ) announcement_join
          ON announcement_join.announcement_id = lp.announcement_id
        
          JOIN (
            SELECT
              DISTINCT ON (p.letters_patent_id) degree,
              p.letters_patent_id AS letters_patent_id,
              p.id AS peerage_id,
              p.of_title AS peerage_of_title,
              p.extinct_on AS peerage_extinct_on,
              p.last_number AS peerage_last_number,
              p.title AS peerage_title,
              r.label AS rank_label,
              pt.id AS peerage_type_id_inline,
              pt.name AS peerage_type_name_inline
            FROM peerages p, ranks r, peerage_types pt
            WHERE p.rank_id = r.id
            AND p.peerage_type_id = pt.id
            ORDER BY p.letters_patent_id, r.degree
          ) peerage_join
          ON peerage_join.letters_patent_id = lp.id
        
          JOIN (
            SELECT
              p.id AS person_id,
              p.forenames as person_forenames,
              p.surname as person_surname,
              p.date_of_death as person_date_of_death
              from people p
          ) person_join
          ON person_join.person_id = lp.person_id
          
          WHERE lp.reign_id = #{self.id}
        
          ORDER BY lp.patent_on, lp.ordinality_on_date;
        "
      )
  end
  
  def date_range
    date_range = self.start_on.strftime( '%-d %B %Y')
    if self.end_on
      date_range += ' until ' + self.end_on.strftime( '%-d %B %Y')
    end
    date_range
  end
end

app/controllers/reign_controller.rb
class ReignController < ApplicationController
  
  def index
    @reigns = Reign.all.select( 'r.*, k.name as kingdom_name' ).joins( 'as r, kingdoms as k' ).where( 'r.kingdom_id = k.id' ).order( 'r.start_on desc' )
  end
  
  def show
    reign = params[:reign]
    @reign = Reign.find( reign )
    @letters_patent = @reign.letters_patents

    respond_to do |format|
      format.html
      format.tsv {
        render :template => 'letters_patent/index'
      }
    end
  end
end

app/helpers/reign_helper.rb
module ReignHelper
end

app/views/reign/_reign.html.erb
<% if reign.monarchs.size == 1 %>
	<p>
		<%= link_to( reign.monarchs.first.name, monarch_show_url( :monarch => reign.monarchs.first ) ) %> monarch of the <%= link_to( reign.kingdom_name, kingdom_show_url( :kingdom => reign.kingdom_id ) ) %> from <%= link_to( reign.date_range, reign_show_url( :reign => reign ) ) %>.
	</p>
<% elsif reign.monarchs.size == 2 %>
	<p>
		<%= link_to( reign.monarchs.first.name, monarch_show_url( :monarch => reign.monarchs.first ) ) %> and <%= link_to( reign.monarchs.second.name, monarch_show_url( :monarch => reign.monarchs.second ) ) %> monarchs of the <%= link_to( reign.kingdom_name, kingdom_show_url( :kingdom => reign.kingdom_id ) ) %> from <%= link_to( reign.date_range, reign_show_url( :reign => reign ) ) %>.
	</p>
<% end -%>

app/views/reign/_reign_from_kingdom.html.erb
<% if reign_from_kingdom.monarchs.size == 1 %>
	<p>
		<%= link_to( reign_from_kingdom.monarchs.first.name, monarch_show_url( :monarch => reign_from_kingdom.monarchs.first ) ) %> monarch of the <%= link_to( reign_from_kingdom.kingdom.name, kingdom_show_url( :kingdom => reign_from_kingdom.kingdom_id ) ) %> from <%= link_to( reign_from_kingdom.date_range, reign_show_url( :reign => reign_from_kingdom ) ) %>.
	</p>
<% elsif reign_from_kingdom.monarchs.size == 2 %>
	<p>
		<%= link_to( reign_from_kingdom.monarchs.first.name, monarch_show_url( :monarch => reign_from_kingdom.monarchs.first ) ) %> and <%= link_to( reign_from_kingdom.monarchs.second.name, monarch_show_url( :monarch => reign_from_kingdom.monarchs.second ) ) %> monarchs of the <%= link_to( reign_from_kingdom.kingdom.name, kingdom_show_url( :kingdom => reign_from_kingdom.kingdom_id ) ) %> from <%= link_to( reign_from_kingdom.date_range, reign_show_url( :reign => reign_from_kingdom ) ) %>.
	</p>
<% end -%>

app/views/reign/_reign_from_monarch.html.erb
<% if reign_from_monarch.monarchs.size == 1 %>
	<p>Monarch of the <%= link_to( reign_from_monarch.kingdom.name, kingdom_show_url( :kingdom => reign_from_monarch.kingdom_id ) ) %> from <%= link_to( reign_from_monarch.date_range, reign_show_url( :reign => reign_from_monarch ) ) %>.</p>
<% else -%>
	<p>Monarch of the <%= link_to( reign_from_monarch.kingdom.name, kingdom_show_url( :kingdom => reign_from_monarch.kingdom_id ) ) %> from <%= link_to( reign_from_monarch.date_range, reign_show_url( :reign => reign_from_monarch ) ) %> with <%= link_to( reign_from_monarch.reign_shared_with( @monarch ).name, monarch_show_url( :monarch => reign_from_monarch.reign_shared_with( @monarch ) ) ) %>.</p>
<% end -%>

app/views/reign/index.html.erb
<%= content_tag( 'h1', 'Reigns' ) %>

<%= render :partial => 'reign', :collection => @reigns %>

app/views/reign/show.html.erb
<h1>
	<% if @reign.monarchs.size == 1 %>
		<%= link_to( @reign.monarchs.first.name, monarch_show_url( :monarch => @reign.monarchs.first ) ) %> monarch of the <%= link_to(@reign.kingdom.name, kingdom_show_url( :kingdom => @reign.kingdom_id ) ) %>
	<% else -%>
		<%= link_to( @reign.monarchs.first.name, monarch_show_url( :monarch => @reign.monarchs.first ) ) %> and <%= link_to( @reign.monarchs.last.name, monarch_show_url( :monarch => @reign.monarchs.last ) ) %> monarchs of the <%= link_to(@reign.kingdom.name, kingdom_show_url( :kingdom => @reign.kingdom_id ) ) %>
	<% end -%>
</h1>
<%= content_tag( 'p', "#{@reign.date_range}." ) %>

<%= content_tag( 'h2', 'Letters Patent' ) %>
<%= content_tag( 'p', link_to( 'Download tab separated', reign_show_url( :format => 'tsv' ) ) ) %>
<table>
	<%= render :partial => 'letters_patent/table_header' %>
	<tbody>
		<%= render :partial => 'letters_patent/letters_patent_table', :collection => @letters_patent %>
</table>